# frozen_string_literal: true

require 'lipgloss'
require 'bubbles'
require_relative 'rview/version'
require_relative 'rview/messages'
require_relative 'rview/styles'
require_relative 'rview/diff_parser'
require_relative 'rview/git_watcher'
require_relative 'rview/config'
require_relative 'rview/baseline_store'
require_relative 'rview/tooling_metrics'
require_relative 'rview/components/file_list'
require_relative 'rview/components/diff_view'
require_relative 'rview/components/status_bar'
require_relative 'rview/components/tooling_box'
require_relative 'rview/app'
